version: '3.7'
services:
  mq:
    image: 'ibmcom/mq'
    ports:
      - '1414:1414'
      - '9443:9443'
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    networks:
      - development
networks:
  development:
